---


- name: Ansible create ec2 instance
  hosts: ['localhost']
  become: yes
  vars_prompt:
    - name: "servername"
      prompt: "Name the server"
      confirm: false
      private: false
    - name: "servertype"
      prompt: "What ec2 type? ex t2.micro"
      confirm: false
      private: false
  tasks:
    - name: Provision instance
      amazon.aws.ec2_instance:
       name: "{{ servername }}"
       aws_access_key: "AKIAY2BFXVI4ABRXDMMS"
       aws_secret_key: "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"
       key_name: "ansible"
         #ImageId: ami-0b854ee84fb0b9c6a
       instance_type: "{{ servertype }}"
       region: us-east-1
       exact_count: 1
       launch_template:
        version: 8
        id: lt-0e0426ff573a09401
       wait: yes


- name: update apt packages
  hosts: ['aws_ec2']
  become: yes
  tasks:
    - name: Wait for system to become reachable
      ansible.builtin.wait_for_connection:
        delay: 60
        timeout: 300
    - meta: refresh_inventory
    - name: Update apt packages
      apt:
       update_cache: yes

    - name: Upgrade all packages on servers
      apt:
        name: "*"
        state: latest

- name: install newrelic agent
  hosts: ['aws_ec2']
  become: yes
  roles:
   - role: newrelic.newrelic-infra
     vars:
       nrinfragent_config:
         license_key: INSERTKEY
         log_file: /var/log/newrelic-infra.log
         log_forward: false
         verbose: 0
         metrics_network_sample_rate: 60
         metrics_storage_sample_rate: 300
         metrics_system_sample_rate: 30
         metrics_nfs_sample_rate: -1
         metrics_process_sample_rate: -1
