- name: Generate ssh key
  hosts: localhost
  connection: local
  become: yes
  vars_prompt:
  - name: "keypath"
    prompt: "Enter ssh key path"
    private: false
    unsafe: true
  - name: "keyname"
    prompt: "Enter ssh key name"
    private: false
  - name: "comment"
    prompt: "Enter comment for username, press enter to skip"
    private: false
  - name: "uid"
    prompt: "Enter uid for user"
    private: false
  tasks:
#- name: generate ssh key
#   community.crypto.openssh_keypair:
#     #path: ' "{{ keypath }}""{{ keyname }}" '
#     path: '{{ keypath }}/{{ keyname }}'
#     type: rsa
#     size: 4096
#     state: present
#     force: no
  - name: Add user account with a primary group of sudoers
    become: true
    ansible.builtin.user:
      name: "{{ keyname }}"
      comment: "{{ comment }}"
      uid: "{{ uid }}"
      group: sudo
      createhome: yes
      home: '/home/{{ keyname }}'

  - name: Create a 2048-bit SSH key for user in requested dir
    ansible.builtin.user:
      name: "{{ keyname }}"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: '{{ keypath }}/{{ keyname }}'

  - name: Set authorized key taken from file
    authorized_key:
      user: "{{ keyname }}"
      state: present
      key: "{{ lookup('file', '{{ keypath }}/{{ keyname }}.pub') }}"
